In [1]:
import numpy as np

def one_hot_encode(y, num_classes):
    m = len(y)
    encoded = np.zeros((m, num_classes))
    encoded[np.arange(m), y] = 1
    return encoded

y = np.array([0,1,2,0,1,2,0,2,1,2,1,0])
print(one_hot_encode(y, num_classes=3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [2]:
import numpy as np
y = np.array([0,1,2,0,1,2,0,2,1,2,1,0])

y_cat_vs_rest = (y==0).astype(int)
print(y_cat_vs_rest)

y_dog_vs_rest = (y==1).astype(int)
print(y_dog_vs_rest)

y_bird_vs_rest = (y==2).astype(int)
print(y_bird_vs_rest)

[1 0 0 1 0 0 1 0 0 0 0 1]
[0 1 0 0 1 0 0 0 1 0 1 0]
[0 0 1 0 0 1 0 1 0 1 0 0]
