In [3]:
import numpy as np

def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

z = np.array([3.0, 1.0, 0.5])
probs = softmax(z)
print(probs)
print(np.sum(probs))

[0.82140902 0.11116562 0.06742536]
0.9999999999999999


In [5]:
import numpy as np

def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

z = np.array([3.0, 2.9, 2.8])
probs = softmax(z)
print(probs)
print(np.sum(probs))

[0.3671654  0.33222499 0.30060961]
1.0


In [7]:
import numpy as np

def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

z = np.array([10.0, 1.0, 0.5])
probs = softmax(z)
print(probs)
print(np.sum(probs))

[9.99801778e-01 1.23385342e-04 7.48369926e-05]
0.9999999999999999


In [8]:
import numpy as np

X = np.array([
    [1, 2, 4, 3],
    [2, 3, 4, 5],
    [5, 2, 1, 4]
])

W = np.zeros((X.shape[1], 3))
b = np.zeros(3)

def hypothesis(X, W, b):
    z = X @ W + b
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

probabilities = hypothesis(X, W, b)

print("Probabilities:\n", probabilities)
print("Row sums:", np.sum(probabilities, axis=1))

Probabilities:
 [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
Row sums: [1. 1. 1.]
