In [1]:
import numpy as np
y = np.array([0,1,2,0,1,2,0,2,1,2,1,0])

y_cat_vs_rest = (y==0).astype(int)
print(y_cat_vs_rest)

y_dog_vs_rest = (y==1).astype(int)
print(y_dog_vs_rest)

y_bird_vs_rest = (y==2).astype(int)
print(y_bird_vs_rest)

[1 0 0 1 0 0 1 0 0 0 0 1]
[0 1 0 0 1 0 0 0 1 0 1 0]
[0 0 1 0 0 1 0 1 0 1 0 0]


In [6]:
import numpy as np

def gradient_descent(X, y, w, b, alpha=0.1, iterations=500):
    for _ in range(iterations):
        z = X @ w + b
        p = 1 / (1 + np.exp(-z))

        dw = (X.T @ (p - y)) / len(y)
        db = np.mean(p - y)

        w -= alpha * dw
        b -= alpha * db

    return w, b, None

num_classes = 3
models = []

X = np.array([
    [1, 2, 4, 3],
    [2, 3, 4, 5],
    [5, 2, 1, 4]
])

y = np.array([0, 1, 2])

for c in range(num_classes):
    y_binary = (y == c).astype(int)
    w = np.zeros(X.shape[1])
    b = 0

    w, b, _ = gradient_descent(X, y_binary, w, b, 0.1, 500)
    models.append((w, b))

print(models)

[(array([-1.60388303, -0.59912052,  2.68408134, -1.89493385]), np.float64(0.5940029097308632)), (array([-2.52325966,  1.21212753, -2.03832834,  2.60730104]), np.float64(-1.4891903792715189)), (array([ 1.68905343, -0.3789802 , -1.65022347, -0.21806008]), np.float64(-0.030522540679222436))]


In [7]:
import numpy as np

def hypothesis(x, w, b):
    return 1 / (1 + np.exp(-(x @ w + b)))


def predict_ovr(x, models):
    probabilities = np.array([
        hypothesis(x, w, b) for w, b in models
    ])
    return np.argmax(probabilities, axis=0)


x = np.array([
    [1, 2, 4, 3],
    [2, 3, 4, 5],
    [5, 2, 1, 4]
])

prediction = predict_ovr(x, models)

print("Prediction:", prediction)

Prediction: [0 1 2]
